### ISSUE TITLE
What should be my first course of action.

### ISSUE THREAD

**Issue by yash7raut** [Gari-Dev-DAO/-Octernship_OS_Contributor_assignment#5]
I have chosen this assignment as a task in github octernship, but I am not understanding what should be my first move. As there isn't any repository where I can look at the open issues to which I may open a pull request. Any help from some maintainer/teacher would be appreciated.

**Comment by Gari-Dev-DAO** [comment]
1)First clone the github repo
2) work in the repo folder
3) add and commit changes
4) push to the main branch

- Or just create a new branch in the same repo with your name and request
