### ISSUE TITLE
still listed on the website?

### ISSUE THREAD

**Issue by exitflynn** [Gari-Dev-DAO/-Octernship_OS_Contributor_assignment#7]
nvm not listed

**Comment by exitflynn** [comment]
nvm no longer listed

**Comment by Gari-Dev-DAO** [comment]
Hey @exitflynn Submission time is already over & if you are starting now it s going to take couple of days & we have to complete the selection process by 1st April. 
But still we would try to consider your application if submitted before 30 March 12 AM IST
